# Generated by Django 3.2.6 on 2021-08-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("permissions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Accounts",
            fields=[
                (
                    "username",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("password", models.CharField(max_length=1000)),
                ("email", models.CharField(max_length=300)),
                (
                    "permissions",
                    models.ManyToManyField(blank=True, to="permissions.Permissions"),
                ),
            ],
        ),
    ]
