run: migrate
	python3 manage.py runserver

test:
	python3 manage.py test

makemigrations:
	python3 manage.py makemigrations

migrate:
	python3 manage.py migrate

install:
	pip install -r requirements/local.txt
