@base = http://localhost:8081
GET {{base}}/api/pizzas

### gültiger POST
POST {{base}}/api/pizzas
Content-Type: application/json

{"pizzaNumber": "P-99", "name": "Kurspizza", "category": "Spezial", "ovenStation": "OFEN-A", "basePrice": 11.5, "active": true}

### ungültiger POST (400)
POST {{base}}/api/pizzas
Content-Type: application/json

{}

### doppelter fachlicher Schlüssel (409)
POST {{base}}/api/pizzas
Content-Type: application/json

{"pizzaNumber": "P-99", "name": "Kurspizza", "category": "Spezial", "ovenStation": "OFEN-A", "basePrice": 11.5, "active": true}
