version: "3"

volumes:
  postgres_data_db_first:

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./docker/prod/Dockerfile
    image: backend_prod
    container_name: backend_db_first_prod
    environment:
      - "DB_HOST=db"
      - "DB_USER=db_first"
      - "DB_NAME=db_first"
      - "DB_PASSWORD=123456"
      - "DATABASE_SELECTION=postgresql"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "127.0.0.1:8000:8000"
    privileged: true
    command: bash -c 'python manage.py migrate && gunicorn backend.wsgi -b 0.0.0.0:8000 -w 2'

  db:
    container_name: db_first_prod
    image: "postgres:13-alpine"
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    volumes:
      - postgres_data_db_first:/var/lib/postgresql/data/
      - ./sql-scripts/init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./sql-scripts:/sql-scripts
    expose:
      - "5432"
    ports:
      - "5432:5432"
