version: "3"

volumes:
  postgres_data_raw_sql:

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./docker/prod/Dockerfile
    image: backend_prod
    container_name: backend_raw_sql_prod
    environment:
      - "DB_HOST=db"
      - "DATABASE_SELECTION=postgresql"
    depends_on:
      - db
    ports:
      - "127.0.0.1:8000:8000"
    privileged: true
    command: bash -c 'python manage.py migrate && gunicorn backend.wsgi -b 0.0.0.0:8000 -w 2'

  db:
    container_name: db_raw_sql_prod
    image: "postgres:13-alpine"
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    volumes:
      - postgres_data_raw_sql:/var/lib/postgresql/data/
    expose:
      - "5432"
    ports:
      - "5432:5432"

  vue_frontend:
    image: vue_frontend_prod
    container_name: vue_frontend_prod
    build:
      context: ./vue-frontend
      dockerfile: ./docker/prod/Dockerfile
    ports:
      - 8080:8080
    environment:
      - VUE_APP_BACKEND_URL=http://backend:8000
    depends_on:
      - backend
