-- Lesbare Relationsnotation, noch kein ausführbares SQLite-Schema
-- restaurants(id PK, partner_number UK, name, commission_rate)
-- TODO(A2): weitere Relationen, PK, FK, UK und NULL/NOT NULL ergänzen.
