@base = http://localhost:8081
GET {{base}}/api/parcels

### gültiger POST
POST {{base}}/api/parcels
Content-Type: application/json

{"trackingCode": "PK-99", "recipient": "Testdatensatz", "weight": 1.0}

### TODO(C3): denselben Wert für tracking_code erneut senden und 409 prüfen
