# Generated by Django 3.2.6 on 2021-08-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Help",
            fields=[
                ("help_id", models.UUIDField(primary_key=True, serialize=False)),
                ("tip", models.CharField(max_length=300)),
            ],
        ),
    ]
