# Generated by Django 3.2.6 on 2021-08-13 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("help", "0002_help_test"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="help",
            name="test",
        ),
    ]
