@base = http://localhost:8081
GET {{base}}/api/venues

### gültiger POST
POST {{base}}/api/venues
Content-Type: application/json

{"venueCode": "V-99", "name": "Kursort", "street": "Kursweg 1", "postalCode": "45127", "city": "Essen", "capacity": 250}

### TODO(C3): denselben Wert für venue_code erneut senden und 409 prüfen
