---
# Main configuration variables for student environment deployment

# Domain configuration
domain_name: "patrick-koss.de"

# Student configuration
student_count: 23

# Repository configuration
repository_url: "https://github.com/PatrickKoss/lecture-ws-development-of-a-db-app.git"
repository_branch: "main"

# Credentials configuration
# credentials_file: "./student-credentials.json"  # Path to existing credentials file
# If not specified, credentials will be generated automatically

# Docker configuration
docker_image_name: "student-vscode"
docker_image_tag: "latest"

# Port configuration
# VSCode servers start at port 8080, API servers start at port 8081
# Each student gets +10 from the previous (student1: 8080/8081, student2: 8090/8091, etc.)
base_vscode_port: 8080
base_api_port: 8081
port_increment: 10

# Nginx configuration
nginx_client_max_body_size: "100M"
nginx_proxy_read_timeout: "86400"
nginx_proxy_send_timeout: "86400"
nginx_proxy_connect_timeout: "60"

# Security configuration
enable_ssl: true  # Set to true to enable SSL/TLS with Let's Encrypt
ssl_email: "patrick.koss@mein.gmx.de"  # Email for Let's Encrypt notifications
# Force redirect HTTP -> HTTPS and set HSTS when SSL is enabled
force_https_redirect: false

# SSL Certificate Strategy
# Options: 'wildcard' (DNS-01 via Cloudflare), 'individual' (HTTP-01), 'mixed'
ssl_cert_strategy: "wildcard"
ssl_use_dns_challenge: true
ssl_dns_propagation_seconds: 60

# Cloudflare API Configuration (required for wildcard certificates)
# cloudflare_api_token: "{{ vault_cloudflare_api_token }}"  # Set in vault or inventory

# Wildcard certificate names
wildcard_api_cert_name: "wildcard-api.{{ domain_name }}"
wildcard_vscode_cert_name: "wildcard-vscode.{{ domain_name }}"

# Logging configuration
log_level: "info"
enable_access_logs: true
enable_error_logs: true

# Environment-specific overrides
# You can override these variables by creating environment-specific files:
# vars/production.yml, vars/staging.yml, vars/development.yml
