spring.application.name=music-school-rest-solution
spring.datasource.url=jdbc:sqlite:music-school-solution.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.hikari.connection-init-sql=PRAGMA foreign_keys=ON
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.open-in-view=false
spring.flyway.enabled=true
server.port=${SERVER_PORT:8081}
server.error.include-message=never
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{correlationId:-}] %logger{36} - %msg%n
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.override-with-generic-response=false
