version: "3"

volumes:
  postgres_data:

services:
  backend_base:
    build:
      context: ./backend
      dockerfile: ./docker/prod/Dockerfile
    image: backend_prod
    container_name: backend_base_prod
    environment:
      - "DB_HOST=db"
    depends_on:
      - db
    ports:
      - "127.0.0.1:8000:8000"
    privileged: true
    command: bash -c 'python manage.py migrate && gunicorn backend.wsgi -b 0.0.0.0:8000 -w 2'

  db_base:
    container_name: db_base_prod
    image: "postgres:13-alpine"
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - "5432"
    ports:
      - "5432:5432"
