spring.application.name=car-workshop-rest
spring.datasource.url=jdbc:sqlite:car-workshop.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.hikari.connection-init-sql=PRAGMA foreign_keys=ON
spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true
server.port=${SERVER_PORT:8081}
server.error.include-message=never
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{correlationId:-}] %logger{36} - %msg%n
