@base = http://localhost:8081
GET {{base}}/api/courses

### gültiger POST
POST {{base}}/api/courses
Content-Type: application/json

{"courseCode": "MU-99", "title": "Songwriting", "fee": 80.0}

### TODO(C3): denselben Wert für course_code erneut senden und 409 prüfen
