-- Lesbare Relationsnotation, noch kein ausführbares SQLite-Schema
-- room_types(id PK, type_code UK, name, standard_price_cents)
-- TODO(A2): weitere Relationen, PK, FK, UK und NULL/NOT NULL ergänzen.
